export const subjects = {
  sem1: {
    it: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    cse: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    ece: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    eee: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    civil: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
    mechanical: [
      "physics",
      "maths",
      "BEE",
      "graphics & design",
      "engg mechanics",
    ],
    mining: ["physics", "maths", "BEE", "graphics & design", "engg mechanics"],
  },

  sem2: {
    it: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    cse: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    ece: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    eee: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    civil: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    mechanical: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
    mining: [
      "chemistry",
      "maths",
      "programming for problem solving",
      "Workshop & Manufacturing Practices",
      "English",
    ],
  },

  sem3: {
    it: [
      "Environmental Science",
      "maths-3",
      "Analog Electronics",
      "DS using C",
      "Computer Architecture & Organization",
    ],
    cse: [
      "Environmental Science",
      "maths-3",
      "Analog Electronics",
      "DS using C",
      "Computer Architecture & Organization",
    ],
    ece: [
      "Managerial Economics and Accountancy",
      "maths-3",
      "Electronics Devices and Circuits",
      "Digital System Design",
      "Signals and Systems",
      "Network Analysis and Synthesis",
      "Constitution of Indian",
    ],
    eee: [
      "maths-3",
      "Electrical Circuits - I",
      "Electrical Machines-I",
      "Power Systems - I",
      "Electromagnetic fields",
      "Analog Electronics",
      "Environmental Sciences",
      "Computer Aided Electrical Drawing Laboratory",
    ],
    civil: [
      "Surveying and Geomatics",
      "maths-3",
      "Introduction to Solid Mechanics",
      "Introduction to Fluid Mechanics",
      "Material Testing and Evaluation",
      "Elements of Mechanical Engineering",
      "Environmental Sciences",
    ],
    mechanical: [
      "Environmental Sciences",
      "maths-3",
      "Thermodynamics",
      "Mechanics of Solids",
      "Material Science and Metallurgy",
      "Manufacturing Science",
      "Applied Electronics",
    ],
    mining: [
      "Mine Development",
      "maths-3",
      "Mine Surveying-I",
      "Mining Geology-I",
      "Basic Electronics Engineering",
      "Environmental Sciences",
    ],
  },

  sem4: {
    it: [
      "Constitution of Indian",
      "Digital Electronics",
      "Mathematical Foundations in Computer Science",
      "Design and Analysis of Algorithms",
      "Operating Systems",
      "OOP Through JAVA",
    ],
    cse: [
      "Constitution of Indian",
      "Digital Electronics",
      "Mathematical Foundations in Computer Science",
      "Design and Analysis of Algorithms",
      "Operating Systems",
      "OOP Through JAVA",
    ],
    ece: [
      "Analog Electronic Circuits",
      "Stochastic Processes",
      "Electromagnetic Waves and Transmission Lines",
      "Pulse and Integrated Circuits",
      "Computer Architecture and Organization",
      "Electronic Measurements and Instrumentation",
      "Environmental Science",
    ],
    eee: [
      "Electrical Circuits II",
      "Electrical Machines - II ",
      "Power System-II",
      "Power Electronics",
      "Digital Electronics and Logic Design",
      "Constitution of India ",
    ],
    civil: [
      "Managerial Economics and Accountancy",
      "Mechanics of Materials",
      "Structural Engineering",
      "Hydraulic Engineering",
      "Hydrology and Water Management",
      "Construction Engineering and Management",
      "Engineering Geology",
    ],
    mechanical: [
      "Thermal Engineering ",
      "Constitution of India",
      "Machine Tools &Metrology",
      "Design of Machine Elements-I",
      "Instrumentation and Control system",
      "Kinematics of Machinery",
      "Machine Drawing",
    ],
    mining: [
      "Mine Ventilation and Planning",
      "Mine Surveying - II",
      "Mining Geology - II",
      "Mechanical Technology",
      "Drilling and Blasting",
      "Constitution of India",
      "Mine Visits",
    ],
  },

  sem5: {
    it: [
      "Database Management Systems",
      "Theory of Computation",
      "Principles of Signals and Systems",
      "Web Programming",
      "Advanced Java",
      "Advanced Data Structures",
      "Managerial Economics and Accountancy",
    ],
    cse: [
      "Database Management Systems",
      "Theory of Computation",
      "Principles of Signals and Systems",
      "Web Programming",
      "Advanced Java",
      "Advanced Data Structures",
      "Managerial Economics and Accountancy",
    ],
    ece: [
      "Control System Engineering",
      "Analog and Digital Communication",
      "Microprocessor and Microcontroller",
      "Antenna Wave Propagation",
      "Digital System Design using Verilog HDL",
      "Bio-Medical Electronics",
      "MOOCS Course",
      "Law and Engineering",
    ],

    eee: [
      "Linear Control Systems",
      "Electrical Machines-III",
      "Linear IC Applications",
      "Utilization of Electrical Energy",
      "PE3105EE High Voltage Engineering",
      "PE3106EE Electric Machine Design",
      "Measurements and Instrumentation",
      "Managerial Economics and Accountancy",
    ],
    civil: [
      "Professional Practice, Building Laws & Ethics",
      "Law and Engineering",
      "Soil Mechanics",
      "Water Resource Engineering",
      "Theory of Structures",
      "Concrete Technology",
      "Disaster Management",
    ],
    mechanical: [
      "Fluid Mechanics & Hydraulic Machines",
      "Dynamics of Machines",
      "Machine Design",
      "Production Planning and Control",
      "Design of Thermal Systems",
      "Non-conventional Energy Sources",
      "Power Plant Engineering",
      "Law and Engineering",
    ],
    mining: [
      "Rock Mechanics",
      "Underground Mining Methods",
      "Mine Hazards and Rescue",
      "Mining Machinery",
      "Mining Instrumentation and Automation",
      "Strength of Materials",
      "Internship - I",
    ],
  },

  sem6: {
    it: [
      "Compiler Design",
      "Computer Networks",
      "Software Engineering",
      "Advanced Database Management System",
      "Advanced Operating System",
      "Computer Graphics",
      "MicroProcessors And Interfacing",
      "Fundamentals Of Data Structures",
    ],
    cse: [
      "Compiler Design",
      "Computer Networks",
      "Software Engineering",
      "Artificial Intelligence",
      "Distributed Databases",
      "Mobile Application Development",
      "MicroProcessors And Interfacing",
      "Fundamentals Of Data Structures",
    ],
    ece: [
      "Digital Signal Processing",
      "VLSI Design",
      "Data Communication and Computer Networks",
      "Embedded System Design",
      "Artificial Neural Networks and Fuzzy Logic",
      "Adaptive Filter Theory and Applications",
      "Optical Communication",
      "Information theory and Coding",
      "Wireless Communications",
      "Radar Engineering",
      "MOOCs Course",
      "Fundamentals Of Data Structures",
    ],
    eee: [
      "Power Semiconductor Drives",
      "Switchgear and Protection",
      "Power System Operation and Control",
      "Electrical Distribution System",
      "Electrical Energy Conservation and Auditing",
      "Hybrid electric vehicles",
      "MOOCS Course",
      "Signals and Linear Systems",
      "Microprocessor Systems",
    ],
    civil: [
      "Environmental Engineering",
      "Design of Steel Structures",
      "Foundation Engineering",
      "Transportation Engg",
      "Design of Irrigation Structures",
      "Air & Noise Pollution and Control",
      "Pavement Construction And Management",
      "Advanced Design Of Concrete Structures",
      "Ground Improvement Techniques",
      "Finite Element Method",
      "Structural Analysis",
      "Pre-Stressed Concrete",
      "Geographic Information System",
      "Green Building Technology",
    ],
    mechanical: [
      "Metal Cutting Science & Unconventional Machining process",
      "Heat Transfer",
      "Refrigeration and Air conditioning",
      "Finite Element Analysis",
      "Fatigue, Creep and Fracture",
      "Theory of Elasticity ",
      "Managerial Economics and Accountancy",
      "MicroProcessors And Interfacing",
      "Fundamentals Of Data Structures",
    ],
    mining: [
      "Mine Ground Control",
      "Under Ground Mining Method(Metal)",
      "Surface Mining Method",
      "Mine Mechanization",
      "Fundamentals of Artificial Intelligence",
      "Mineral Exploration & Reserve Estimation",
      "Mine Surface Environment Management",
      "Rock Excavation Engineering",
    ],
  },

  sem7: {
    it: [
      "Python",
      "Software Testing",
      "Object Oriented Analysis and Design",
      "Artificial Intelligence",
      "Mobile Application Development",
      "Cryptography& Information Security",
      "Big Data Analytics",
    ],
    cse: [
      "Python",
      "Software Testing",
      "Object Oriented Analysis and Design",
      "Machine Learning",
      "Soft Computing",
      "Cryptography& Network Security",
      "Cloud Computing",
    ],
    ece: [
      "Microwave Engineering",
      "Satellite Communications",
      "Wavelet Theory and Applications",
      "Fault Detection in Digital Systems",
      "Digital Image Processing",
      "Internet of Things",
      "Low Power VLSI Design",
      "Disaster Management",
      "Non-Conventional Energy sources",
      "Startup Entrepreneurship",
    ],
    eee: [
      "Power System Analysis",
      "Flexible AC Transmission System",
      "Industrial Electrical Systems",
      "Power System Reliability",
      "Digital Control System",
      "HVDC Transmission System",
      "Power Quality Engineering",
      "Disaster Management",
      "Computer Organization",
      "Digital Signal Processing",
      "VLSI Design",
    ],
    civil: [
      "Estimation Costing and Specification",
      "Analysis and Design of Bridges",
      "Applied Hydrology",
      "Road Safety Engineering",
      "Retrofitting and Rehabilitation of Structures",
      "Elements of Earth Quake Engineering",
      "Finite Element Analysis",
      "Railway Infrastructure Planning and Design",
      "Ground Water Management",
      "Intelligent Transportation System",
      "Optimization Techniques",
      "Fundamentals of IOT",
      "Basic Material Science and Engineering",
      "IPR and Patenting",
    ],
    mechanical: [
      "CAD / CAM",
      "Industrial Automation",
      "Advanced Material Science and Engineering ",
      "Computational Fluid Dynamics",
      "Mechatronics",
      "Tool Design",
      "Additive Manufacturing",
      "Design for Manufacturing",
      "Fuel Cell Technology",
      "Energy Storage Systems",
      "Optimization Techniques",
      "Fundamentals of IoT",
    ],
    mining: [
      "Mine Planning",
      "Numerical Modeling in Mining",
      "Mineral Processing",
      "Mineral Processing Laboratory",
      "Numerical Modeling in Mining Lab",
      "Survey & Geological camp",
      "Human Resource Management",
      "Cyber Law and ethics",
      "Intellectual Property Rights",
    ],
  },
};
